version: '3'

services:
  backend:
    container_name: backend-server
    image: dockerhub_id/app-with-actions:latest
    ports:
      - 8080:8080
    environment:
      spring.datasource.url=${SPRING_DATASOURCE_URL}
      spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
      spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
