version: '3'

services:
  backend:
    container_name: backend-server
    image: hjukeboxox/app-with-actions:latest
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
