
services:
  backend:
    container_name: backend-server
    image: ${DOCKERHUB_USERNAME}/app-with-actions:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
