
services:
  backend:
    container_name: backend-server
    image: "116981781177.dkr.ecr.ap-northeast-2.amazonaws.com/first-private-ecr:f140970dfad53331413a1be105153af8e87a0f7f"
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
